-Реализация стандартных действий и представлений для ресурса вопросов.
DAndreevskikh/Test_Guru pull request #7
Opened 2024-01-17 23:15 UTC by DAndreevskikh

Включено отображение списка вопросов на странице теста, использование фрагментов представлений, настройка form_with для правильной генерации URL, и добавление навигационных ссылок. Добавлен футер с информацией о текущем годе, авторе и ссылкой на проект GitHub. Созданы хелперы для заголовков форм и генерации ссылок GitHub. В список тестов интегрировано отображение количества вопросов.

2024-01-18 05:22 UTC, VidgarVii requested changes

2024-01-18 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id])
этот запрос уже вызывается в колбеке

2024-01-18 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
и этот запрос уже вызывается в колбеке

2024-01-18 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  find_question
надо разобраться в работе колбеков!

2024-01-18 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = @question.present? ? @question.test : Test.find(params[:test_id])
так не работают.
Не надо вызываться этот метод через колбек, там где не приходит параметр test_id. И все эти проверки будут не нужны

2024-01-18 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    before_action :find_test, only: %i[index create new]
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2024-01-18 05:22 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +end
стоит до делать контроллер, как QuestionsController

2024-01-18 05:22 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +  <p><a href="https://thinknetica.com">Учебный проект в онлайн-школе Thinknetica</a></p>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2024-01-18 05:22 UTC, VidgarVii commented on app/views/questions/_question.html.erb
> +</div>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-01-18 05:22 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +<% @questions.each do |question| %>
для рендера коллекций обычно используют render collection
http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy

```ruby
  render @questions
```

- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своей папке
- Позволит удобней кешировать куски страницы

в скринкасте про лэйауты и паршелы рассказывается про рекомендуемый вариант рендеринга коллекций (примерно после 20:30)

2024-01-18 05:22 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<% form_url = @question.persisted? ? question_path(@question) : test_questions_path(@test) %>
не нужно писать услоный блок
просто пишешь `form_with model: [@test, @question]`
для эдит переменная `@test` будет пустая (не надо ее в контроллере искать, т.к. при использовании опции "шеллоу тру" в роутах для эдит `@test` не нужен)
соответсвенно в `@test` будет "нил" и рельсы построят правильный путь, потому что придет только `@question`
для нью придут оба объекта ("тест" и "квесшен") и рельсы также построят правильный путь

2024-01-25 04:51 UTC, VidgarVii requested changes

2024-01-25 04:51 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +end
no new line at end file

2024-01-25 04:51 UTC, VidgarVii commented on app/helpers/application_helper.rb
> + end
тут надо поправить отступы

2024-01-25 04:51 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +end
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-01-25 04:51 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: [:new, :create]
надо убрать маршурт для index вопроса, так как этого экшено больше нет

2024-01-25 04:51 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +  <% @test.questions.each_with_index do |question, index| %>
для перечислений всегда используют рендер коллекций, а не each
Вот тут верно его используешь https://github.com/DAndreevskikh/Test_Guru/pull/7/files
- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своей папке
- Позволит удобней кешировать куски страницы

2024-01-25 04:51 UTC, VidgarVii commented on app/views/tests/_test.html.erb
> +    <%= link_to 'Удалить', test_path(test), method: :delete, data: { confirm: 'Вы уверены?' } %>
стоит перепроверить работу ссылки

2024-01-26 13:57 UTC, VidgarVii requested changes

2024-01-26 13:57 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i[show start edit update destroy]
Нет смысла списывать чужой код не разобравшись что он делает =( 
Задача должна быть научиться самим работать с рельсой, а не нажимать ctrl+C ctrl+V
В итоге: 
1 замечания не были исправлены
2 ruby stytle не соблюдается. rubocop не используется. Пишу про это уже не в 1 раз =(
3 Появился код, которого нет в тз и который не работает.

2024-01-26 13:57 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @questions_with_index = @test.questions.each_with_index.map do |question, index|
Есть решение на много элегантней и проще
https://rusrails.ru/layouts-and-rendering#peremennye-schetchika

2024-02-05 15:03 UTC, VidgarVii requested changes

2024-02-05 15:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_path(@test), notice: 'Вопрос создан'
обычно принято после сохранения/обновления ресурса показывать этот ресурс. В ТЗ не сказано, что нужно показывать тест после сохранения вопроса

2024-02-05 15:03 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_path(@question.test), notice: 'Вопрос обновлен'
тоже самое

2024-02-05 15:03 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +  <p><a href="https://thinknetica.com" target="_blank" rel="nofollow noopener">Учебный проект в онлайн-школе Thinknetica</a></p>
для ссылок есть удобный хелпер link_to

2024-02-05 15:03 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    "#{action} #{question.test&.title || 'Test'} Question"
вопрос не может быть без теста

2024-02-06 06:44 UTC, VidgarVii requested changes

2024-02-06 06:44 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions, shallow: true, except: :show
точно не show надо убирать

2024-02-06 06:44 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_path(@test), notice: 'Вопрос создан'
не исправлено

2024-02-06 06:44 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_path(@question.test), notice: 'Вопрос обновлен'
не исправлено

2024-02-06 09:57 UTC, DAndreevskikh commented on config/routes.rb
> +    resources :questions, shallow: true, only: %i[new create show edit update destroy]
Можно уточнить?
"убрать лишний экшен для вопросов" - убрать всё же имеется ввиду "except"..или сделать ограничение будет правильным? Не совсем понимаю, если нужно исключение, то для какого экшена. т.к. они все используются. Или я что-то не так понимаю

2024-02-06 14:30 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions, shallow: true, only: %i[new create show edit update destroy]
в данном случаи можно было использовать except. Просто до этого был убран нужный экшен

2024-02-07 09:45 UTC, merged